-- MySQL Script generated by MySQL Workbench
-- 11/23/18 16:14:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`recibo1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recibo1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `dataemissao` DATE NOT NULL,
  `table1col` VARCHAR(45) NOT NULL,
  `prestador_fk` INT NOT NULL,
  `emitente_fk` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recibo_pessoa_idx` (`prestador_fk` ASC),
  INDEX `fk_recibo_pessoa1_idx` (`emitente_fk` ASC),
  CONSTRAINT `fk_recibo_pessoa`
    FOREIGN KEY (`prestador_fk`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recibo_pessoa1`
    FOREIGN KEY (`emitente_fk`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
